create database bank;
USE BANK;

CREATE TABLE ACCOUNT(NAME VARCHAR(20), ACC_NO VARCHAR(20), DOB VARCHAR(30), ADDRESS VARCHAR(20), PHONE INT, OPENING_BALANCE INT);
CREATE TABLE AMOUNT(NAME VARCHAR(20), ACC_NO VARCHAR(20),  BALANCE INT);

DESC AMOUNT;
DESC ACCOUNT;

select * from amount;
select * from account;
